CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users(
   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   is_admin BOOLEAN DEFAULT FALSE,
   is_member BOOLEAN DEFAULT FALSE
);

CREATE TABLE posts(
   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   title VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE
);